apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: outline
  namespace: fleet-local
spec:
  helm:
    pollingInterval: 1m
    repo: oci://harbor.ryzen.me/library/outline
    version: 0.1.0
    values:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: cert-issuer
        host: outline.ryzen.me
        tls:
          secretName: outline-tls
      storage:
        s3:
          enabled: false
        size: 30Gi
        storageClassName: retain
      oidc:
        enabled: true
        issuerUrl: https://auth.ryzen.me/realms/public
        clientId: outline
        secret:
          existing: true
          name: outline-oidc-secret
          clientSecretKeyRef: OIDC_CLIENT_SECRET
  defaultNamespace: outline