{{ if .Values.storage.s3.enabled }}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ printf "%s-s3" (include "outline.fullname" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  repo: {{ .Values.storage.s3.chart.repo }}
  chart: {{ .Values.storage.s3.chart.name }}
  targetNamespace: {{ .Release.Namespace }}
  createNamespace: true
  valuesContent: |-
    replicas: {{ .Values.storage.s3.replicas }}
    mode: {{ .Values.storage.s3.mode }}
    persistence:
      size: {{ .Values.storage.s3.persistence.size }}
    buckets:
      - name: {{ .Values.storage.s3.bucket }}
        policy: upload
    users:
      - accessKey: {{ .Values.storage.s3.accessKey }}
        existingSecret: {{ include "outline.secretName" . }}
        existingSecretKey: {{ .Values.storage.s3.secretKeyRef }}
        policy: readwrite
{{ end }}
