apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "outline.name" . }}
  name: {{ include "outline.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "outline.name" . }}
  strategy:
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ include "outline.name" . }}
    spec:
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      containers:
        - image: {{ print .Values.image.repository ":" .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: outline
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          {{ if .Values.ingress.tls }}
          - name: URL
            value: {{ print "https://" .Values.ingress.host }}
          {{ else }}
          - name: URL
            value: {{ print "http://" .Values.ingress.host }}
          {{ end }}
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "outline.dbSecretName" . }}
                key: {{ .Values.database.secret.urlKey }}
          - name: SMTP_FROM_EMAIL
            value: {{ .Values.outline.smtp.fromEmail | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.outline.logLevel | quote }}
          - name: FORCE_HTTPS
            value: {{ .Values.outline.forceHttps | quote }}
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "outline.secretName" . }}
                key: SECRET_KEY
          - name: UTILS_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "outline.secretName" . }}
                key: UTILS_SECRET
{{ if .Values.redis.enabled }}
          - name: REDIS_URL
            value: {{ include "outline.redisUrl" . | quote }}
{{ end }}
{{ if .Values.oidc.enabled }}
          - name: OIDC_ISSUER_URL
            value: {{ .Values.oidc.issuerUrl }}
          - name: OIDC_CLIENT_ID
            value: {{ .Values.oidc.clientId }}
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "outline.oidcSecretName" . }}
                key: {{ .Values.oidc.secret.clientSecretKeyRef }}
{{ end }}
{{ if .Values.storage.s3.enabled }}
          - name: FILE_STORAGE
            value: s3
          - name: AWS_ACCESS_KEY_ID
            value: {{ .Values.storage.s3.accessKey | quote }}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "outline.secretName" . }}
                key: {{ .Values.storage.s3.secretKeyRef }}
          - name: AWS_REGION
            value: {{ .Values.storage.s3.region }}
          - name: AWS_S3_UPLOAD_BUCKET_URL
            value: {{ include "outline.s3Endpoint" . | quote }}
          - name: AWS_S3_UPLOAD_BUCKET_NAME
            value: {{ .Values.storage.s3.bucket | quote }}
          - name: AWS_S3_FORCE_PATH_STYLE
            value: {{ .Values.storage.s3.pathStyle | quote }}
{{ else }}
          - name: FILE_STORAGE
            value: local
{{ end }}
{{- with .Values.outline.extraEnv }}
          {{- toYaml . | nindent 10 }}
{{- end }}
{{ if not .Values.storage.s3.enabled }}
          volumeMounts:
            - name: outline
              mountPath: /var/lib/outline/data
      volumes:
        - name: outline
          persistentVolumeClaim:
            claimName: {{ printf "%s-pvc" (include "outline.fullname" .) }}
{{ end }}
      restartPolicy: Always
