{{ if .Values.redis.enabled }}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ printf "%s-redis" (include "outline.fullname" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  repo: {{ .Values.redis.chart.repo }}
  chart: {{ .Values.redis.chart.name }}
  targetNamespace: {{ .Release.Namespace }}
{{ end }}
